[book]
title = "PallasDB - Technical Documentation"
authors = ["Teddy Malhan"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/teddymalhan/pallasdb"
edit-url-template = "https://github.com/teddymalhan/pallasdb/edit/main/mdbook-book/src/{path}"
